# 项目相关配置
data-factory:
  # 名称
  name: data-factory
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/data-factory/uploadPath，Linux配置 /home/data-factory/uploadPath）
#  profile: D:/Zhangr/IDEA work space/data-factory/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  session:
    #设置session有效时长7200s(2个小时)
    timeout: 7200
  servlet:
    # 应用的访问路径
    context-path: /
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # 连接数满后的排队数，默认为100
#    accept-count: 1000
#    threads:
#      # tomcat最大线程数，默认为200
#      max: 800
#      # Tomcat启动初始化的线程数，默认值10
#      min-spare: 100

# 日志配置
logging:
  level:
    com.data: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #serverTimezone=GMT%2B8 与 serverTimezone=Asia/Shanghai 功能相同
    url: jdbc:mysql://localhost:3306/data_factory?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传
  servlet:
    multipart:
      #启用文件上传功能
      enabled: true
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 47.120.73.26
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 0P0rcq2m
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #设置空如何序列化
    default-property-inclusion: non_null
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

#template:
#  file:
#    path: ../../../../模板.xlsx


main:
  #关闭SpringBoot启动图标(banner)
  banner-mode:off

## Sa-Token 配置
#sa-token:
#  # token 名称（同时也是 cookie 名称）
#  token-name: satoken
#  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
#  timeout: 2592000
#  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
#  active-timeout: -1
#  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
#  is-concurrent: true
#  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
#  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
#  token-style: uuid
#  # 是否输出操作日志
#  is-log: true

# token配置
#token:
#  # 令牌自定义标识
#  header: Authorization
#  # 令牌密钥
#  secret: abcabcdefhghijklnmoqprstuvwvxyz
#  # 令牌有效期（默认30分钟）
#  expireTime: 30

# MyBatis配置
mybatis-plus:
  # 加载全局的配置文件
  configuration:
    #打印SQL到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #关闭mybatisplus启动图标
    banner: off
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

## 防止XSS攻击
#xss:
#  # 过滤开关
#  enabled: true
#  # 排除链接（多个用逗号分隔）
#  excludes: /system/notice
#  # 匹配链接
#  urlPatterns: /system/*,/monitor/*,/tool/*